config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'public#homepage', as: :homepage

  scope '', format: false do
    get '/logout', to: 'signin#logout', as: :logout
    scope '/signin' do
      get '', to: 'signin#signin', as: :signin
      post '', to: 'signin#signin_submit', as: :signin_submit
    end

    scope 'shop' do
      scope '/:category_slug' do
        get '', to: 'shop#category', as: :category
        scope '/:product_slug' do
          get '', to: 'shop#product', as: :product
        end
      end
    end

    scope 'members' do
      get '', to: 'members#dashboard', as: :members_dashboard
    end

    resources :favorite_products, only: %i[create destroy]

    match '*unmatched', to: 'application#not_found_method', via: :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name, :slug
  validates_uniqueness_of :slug

  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/favorite_product.rb
class FavoriteProduct < ApplicationRecord
  validates_presence_of :product_id, :user_id
  validates_uniqueness_of :product_id, scope: :user_id

  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :slug, :price_usd, :image_url
  validates_uniqueness_of :slug

  has_many :product_categories
  has_many :categories, through: :product_categories

  scope :active, -> { where(is_active: true) }
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
  validates_presence_of :product_id, :category_id
  validates_uniqueness_of :product_id, scope: :category_id
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt

  attr_accessor :password

  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true
  has_secure_password

  has_many :user_logins
  has_many :favorite_products
  has_many :favorites, through: :favorite_products, source: :product

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_digest = @password
  end
end

app/models/user_login.rb
class UserLogin < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id, :login_at

  scope :ordered, -> { order(login_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected

  helper_method :signed_in?, :current_user

  def sign_in!(user)
    UserLogin.create(user: user, login_at: Time.now)
    session[:user_id] = user.id
  end

  def signed_in?
    !session[:user_id].nil?
  end

  def current_user
    @user ||= signed_in? ? User.find(session[:user_id]) : User.new
  end

  def authenticate_user!
    unless signed_in?
      flash[:error] = 'Authentication Required to Continue'
      return redirect_to homepage_path(redirect_to: request.original_url)
    end
  end

  def render_not_found
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  class InvalidPasswordError < StandardError; end

  def auth_user
    user = User.find_by!(email: params[:email])
    raise InvalidPasswordError unless user.password == params[:password]
    sign_in! user
    flash[:success] = 'Welcom back, %s!' % user.email
    redirect_to params[:redirect_to] || members_dashboard_path
  rescue ActiveRecord::RecordNotFound, InvalidPasswordError => e
    flash[:error] = 'Username and/or Password are incorrect'
    redirect_to homepage_path
  end

  def logout
    session.destroy
    redirect_to homepage_path
  end

end

app/controllers/favorite_products_controller.rb
class FavoriteProductsController < ApplicationController
  before_action :set_product

  def create
    if FavoriteProduct.create(product: @product, user: current_user)
      flash[:success] = 'Product has been favorited'
    else
      flash[:error] = 'Something went wrong'
    end

    redirect_back(fallback_location: homepage_path)
  end

  def destroy
    FavoriteProduct.where(product_id: @product.id, user_id: current_user.id).first.destroy
    flash[:success] = 'Product has been deleted from favorites'
    redirect_back(fallback_location: homepage_path)
  end

  private

  def set_product
    @product = Product.active.find(params[:product_id] || params[:id])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def category
    category_slug = params.require([:category_slug])
    @category = Category.find_by!(slug: category_slug)
  end

  def product
    category_slug, product_slug = params.require([:category_slug, :product_slug])
    @category = Category.find_by!(slug: category_slug)
    @product = @category.products.find_by(slug: product_slug)

    render_not_found unless @product&.is_active?
  end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  class InvalidPasswordError < StandardError; end

  def signin_submit
    user = User.find_by!(email: params[:email])
    raise InvalidPasswordError unless user.password == params[:password]
    sign_in! user
    flash[:success] = 'Welcome back, %s!' % user.email
    redirect_to params[:redirect_to] || members_dashboard_path
  rescue ActiveRecord::RecordNotFound, InvalidPasswordError => e
    flash[:error] = 'Username and/or Password are incorrect'
    redirect_to homepage_path
  end

  def logout
    session.destroy
    flash[:success] = 'You have been signed out'
    redirect_to homepage_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="shadow bg-sky-950 w-full">
      <div class="h-16 mx-auto px-5 flex items-center justify-between">
          <a href="/" class="text-2xl font-bold text-sky-200">Logo Here</a>
          
          <ul class="flex items-center gap-5">
            <% if signed_in? %>
            <li><a class="text-sky-200 font-bold" href="<%= logout_path %>">Sign Out</a></li>
            <% else %>
            <li><a class="text-sky-200 font-bold" href="<%= signin_path %>">Sign In</a></li>
            <% end %>
          </ul>
      </div>
    </header>

    <main class="container w-6/12 mx-auto flex">
      <div class="container ">
        <% if flash[:success] %><div class="rounded-md border-green-400 border-solid border-x-2 border-y-2 bg-green-100 p-5 mb-10 mt-2"><%= flash[:success] %></div><% end %>

        <%= yield %>
      </div>
    </main>

    <div class="flex items-end w-full h-full bg-white">
      <footer class="w-full text-sky-200 bg-sky-700 border-t border-t-sky-950 body-font">
          <div
              class="container flex flex-col flex-wrap px-5 py-24 mx-auto md:items-center lg:items-start md:flex-row md:flex-no-wrap">
              <div class="flex-shrink-0 w-64 mx-auto text-center md:mx-0 md:text-left">
                  <a class="flex items-center justify-center font-medium text-gray-900 title-font md:justify-start">
                    ExampleCompany
                  </a>
                  <p class="mt-2 text-sm text-sky-300">Design, Code and Ship!</p>
                  <div class="mt-4">
                      <span class="inline-flex justify-center mt-2 sm:ml-auto sm:mt-0 sm:justify-start">
                          <a class="text-sky-300 cursor-pointer hover:text-gray-700">
                              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  class="w-5 h-5" viewBox="0 0 24 24">
                                  <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                              </svg>
                          </a>
                          <a class="ml-3 text-sky-300 cursor-pointer hover:text-gray-700">
                              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  class="w-5 h-5" viewBox="0 0 24 24">
                                  <path
                                      d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z">
                                  </path>
                              </svg>
                          </a>
                          <a class="ml-3 text-sky-300 cursor-pointer hover:text-gray-700">
                              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                  stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                  <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                                  <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                              </svg>
                          </a>
                          <a class="ml-3 text-sky-300 cursor-pointer hover:text-gray-700">
                              <svg fill="currentColor" stroke="currentColor" stroke-linecap="round"
                                  stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
                                  <path stroke="none"
                                      d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z">
                                  </path>
                                  <circle cx="4" cy="4" r="2" stroke="none"></circle>
                              </svg>
                          </a>
                      </span>
                  </div>
              </div>
              <div class="flex flex-wrap flex-grow mt-10 -mb-10 text-center md:pl-20 md:mt-0 md:text-left">
                  <div class="w-full px-4 lg:w-1/4 md:w-1/2">
                      <h2 class="mb-3 text-sm font-medium tracking-widest text-gray-900 uppercase title-font">About</h2>
                      <nav class="mb-10 list-none">
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Company</a>
                          </li>
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Careers</a>
                          </li>
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Blog</a>
                          </li>
                      </nav>
                  </div>
                  <div class="w-full px-4 lg:w-1/4 md:w-1/2">
                      <h2 class="mb-3 text-sm font-medium tracking-widest text-gray-900 uppercase title-font">Support</h2>
                      <nav class="mb-10 list-none">
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Contact Support</a>
                          </li>
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Help Resources</a>
                          </li>
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Release Updates</a>
                          </li>
                      </nav>
                  </div>
                  <div class="w-full px-4 lg:w-1/4 md:w-1/2">
                      <h2 class="mb-3 text-sm font-medium tracking-widest text-gray-900 uppercase title-font">Platform
                      </h2>
                      <nav class="mb-10 list-none">
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Terms &amp; Privacy</a>
                          </li>
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Pricing</a>
                          </li>
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">FAQ</a>
                          </li>
                      </nav>
                  </div>
                  <div class="w-full px-4 lg:w-1/4 md:w-1/2">
                      <h2 class="mb-3 text-sm font-medium tracking-widest text-gray-900 uppercase title-font">Contact</h2>
                      <nav class="mb-10 list-none">
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Send a Message</a>
                          </li>
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">Request a Quote</a>
                          </li>
                          <li class="mt-3">
                              <a class="text-sky-300 cursor-pointer hover:text-gray-900">+123-456-7890</a>
                          </li>
                      </nav>
                  </div>
              </div>
          </div>
          <div class="bg-sky-800">
              <div class="container px-5 py-4 mx-auto">
                  <p class="text-sm text-sky-300 capitalize xl:text-center">© <%= Time.now.year %> All rights reserved </p>
              </div>
          </div>
      </footer>

    </div>

  </body>
</html>

app/views/members/dashboard.html.erb
<div class="flex flex-col mt-10 mb-10">
  <h1 class="text-4xl">Member Dashboard</h1>
  <div class="border-t border-gray-400 w-full"></div>
  <div class="flex flex-row justify-between">
    <div class="flex flex-col w-1/2">
      <div class="m-2 border border-gray-400 shadow-md rounded-md p-4">
        <h2 class="text-xl font-bold">Profile Details:</h2>
        <ul>
          <li>Email: <%= current_user.email %></li>
          <li>Created At: <%= current_user.created_at %></li>
          <li>Updated At: <%= current_user.updated_at %></li>
        </ul>
      </div>
    </div>
    <div class="flex flex-col w-1/2 h-full">
      <div class="m-2 border border-gray-400 shadow-md rounded-md p-4">
        <h2 class="text-xl font-bold">Login History:</h2>
        <ul>
          <% current_user.user_logins.ordered.each do |login| %>
            <li><%= login.login_at %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <% current_user.favorites.active.any? do %>
    <div class="flex flex-row">
      <div class="m-2 border border-gray-400 shadow-md rounded-md p-4 w-full">
        <h2 class="text-xl font-bold">Favorite products:</h2>

        <%= render partial: "shared/product_small_card", collection: current_user.favorites.active, as: :product %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_favorite_button.html.erb
<div class="w-5">
  <% if signed_in? %>
    <% if current_user.favorite_products.exists?(product_id: product.id) %>
      <%= button_to favorite_product_path(product), method: :delete do %>
        <%= image_tag "icons/heart_full.svg", class: "w-full", alt: "heart icon" %>
      <% end %>
    <% else %>
      <%= button_to favorite_products_path(product_id: product) do %>
        <%= image_tag "icons/heart.svg", class: "w-full", alt: "heart icon" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_product_small_card.html.erb
<div
  class="flex flex-row items-center my-4 rounded-lg bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]"
>
  <img class="w-28 rounded-l-lg" src="<%= image_url product.image_url %>" alt="Photo of <%= product.name %>" />
  <div class="flex flex-row justify-between w-full">
    <p class="text-md font-medium leading-tight text-neutral-800 ml-4">
      <a href="<%= product_path(category_slug: product.categories.first.slug, product_slug: product.slug) %>">
        <%= product.name %>
      </a>
    </p>
    <div class="mr-4">
      <%= render "shared/favorite_button", product: product %>
    </div>
  </div>
</div>

app/views/shop/category.html.erb
<div class="max-w-[1100px] flex flex-col">
  <h2 class="text-2xl font-bold border-b border-r-sky-950 pb-1 mb-2"><%= @category.name %></h2>
  <div class="pb-4">
    <a href="/">Home</a>
    <span class="mx-2 text-gray-600">/</span>
    <%= @category.name %>
  </div>
  <div class="flex flex-row flex-wrap">
    <% @category.products.active.each do |product| %>
    <div
      class="block w-1/2 my-4 px-3 pt-3 rounded-lg bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]">
      <a href="<%= product_path(category_slug: @category.slug, product_slug: product.slug) %>">
        <img
          class="rounded-t-lg"
          src="<%= image_url product.image_url %>" alt="Photo of <%= product.name %>"
        />
      </a>
      <div class="p-6">
        <div class="flex flex-row justify-between">
          <h5
            class="mb-2 text-xl font-medium leading-tight text-neutral-800 ">
            <%= product.name %>
          </h5>
          <%= render "shared/favorite_button", product: product %>
        </div>

        <p class="mb-4 text-base text-neutral-600 ">
          <%= product.description %>
        </p>
        <a
          href="<%= product_path(category_slug: @category.slug, product_slug: product.slug) %>"
          class="inline-block rounded bg-sky-900 px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] dark:shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] "
          data-te-ripple-init
          data-te-ripple-color="light">
          Details
        </a>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shop/product.html.erb
<div class="max-w-[1100px] flex flex-col">
  <h2 class="text-2xl font-bold border-b border-r-sky-950 pb-1 mb-2"><%= @category.name %></h2>
  <div class="pb-4">
    <a href="/">Home</a>
    <span class="mx-2 text-gray-600">/</span>
    <a href="<%= category_path(category_slug: @category.slug) %>"><%= @category.name %></a>
    <span class="mx-2 text-gray-600">/</span>
    <%= @product.name %>
  </div>
  <div class="flex flex-row flex-wrap">
    <div
      class="block w-full mx-auto my-4 px-3 rounded-lg bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]">
      <img
        class="rounded-t-lg"
        src="<%= image_url @product.image_url %>" alt="Photo of <%= @product.name %>"
      />
      <div class="p-6">
        <div class="flex flex-row justify-between items-center mb-2">
          <h5
            class="mb-2 text-xl font-medium leading-tight text-neutral-800 ">
            <%= @product.name %>
          </h5>
          <%= render "shared/favorite_button", product: @product %>
        </div>
        <div class="flex flex-row">
          <% @product.categories.each do |category| %>
            <p
              class="text-sm bg-sky-100 rounded mb-4 mr-2 px-2 py-2 hover:bg-sky-200 active:bg-sky-800">
              <a href="<%= category_path(category_slug: category.slug) %>"><%= category.name %></a>
            </p>
          <% end %>
        </div>
        <p class="mb-4 text-base text-neutral-600 ">
          <%= number_to_currency(@product.price_usd) %>
        </p>
        <p class="mb-4 text-base text-neutral-600 ">
          <%= @product.description %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/signin/signin.html.erb
<div class="min-h-[800px] flex flex-col justify-center sm:py-12">
  <div class="p-10 xs:p-0 mx-auto md:w-full md:max-w-md">
    <h1 class="font-bold text-center text-2xl mb-5">Example App</h1>  
    <% if flash[:error] %><div class="rounded-md border-red-500 border-solid border-x-2 border-y-2 bg-red-300 p-5 mb-10"><%= flash[:error] %></div><% end %>
    <div class="bg-white shadow w-full bg-sky-100 rounded-lg divide-y divide-sky-300">
      <%= form_tag signin_submit_path, autocomplete: :off do |f| %>
      <div class="px-5 py-7">
        <label class="font-semibold text-sm text-gray-600 pb-1 block">E-mail</label>
        <input type="email" name="email" required autocomplete="off" class="border rounded-lg px-3 py-2 mt-1 mb-5 text-sm  focus:border-sky-700 w-full" />
        <label class="font-semibold text-sm text-gray-600 pb-1 block">Password</label>
        <input type="password" name="password" required autocomplete="off" class="border rounded-lg px-3 py-2 mt-1 focus:border-sky-700 mb-5 text-sm w-full" />
        <button type="submit" class="transition duration-200 bg-sky-500 hover:bg-sky-600 focus:bg-sky-700 focus:shadow-sm focus:ring-4 focus:ring-blue-500 focus:ring-opacity-50 text-white w-full py-2.5 rounded-lg text-sm shadow-sm hover:shadow-md font-semibold text-center inline-block">
            <span class="inline-block mr-2">Login</span>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4 inline-block">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
            </svg>
        </button>
      </div>
      <% end %>
    </div>
  </div>
</div>